# Generated by Django 2.2 on 2019-12-03 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search_Book',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('mobile_no', models.IntegerField()),
                ('address', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_type', models.CharField(max_length=30)),
                ('book_price', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('renewal_date', models.DateField()),
                ('author_name', models.CharField(max_length=25)),
                ('publication_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibrarySystem.User')),
            ],
        ),
    ]
